weidu --nogame 	--untraify-d gorgon\dialog\h_aishad.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_amriud.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_ariosd.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_asnabd.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_bald2d.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_baldwd.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_borlad.D				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_carn0d.D				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_carn3d.D				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_carn4d.D				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_carn5d.D				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_carthd.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_cmaidd.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_danikd.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_denebd.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_europd.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_eurynd.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_flam2d.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_galatd.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_game2d.D				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_game3d.D				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_gamesd.D				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_gellad.D				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_gerard.D				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_gilbad.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_hunted.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_ilenad.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_injurd.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_isleyd.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_kageid.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_karpdd.D				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_katred.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_lieded.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_lotusd.D				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_magnud.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_meredd.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_nagatd.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_nobled.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_opheld.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_quassd.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_rich2d.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_richad.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_rigald.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_rogued.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_saradd.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_smuggd.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_thamud.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_tuztdd.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_vapuld.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_xevecd.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_yumild.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_zedadd.d				--untraify-tra gorgon\lang\english\dialog.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_zhontd.d				--untraify-tra gorgon\lang\english\dialog.tra

weidu --nogame 	--untraify-d gorgon\dialog\h_aishad.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_amriud.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_ariosd.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_asnabd.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_bald2d.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_baldwd.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_borlad.D				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_carn0d.D				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_carn3d.D				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_carn4d.D				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_carn5d.D				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_carthd.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_cmaidd.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_danikd.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_denebd.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_europd.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_eurynd.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_flam2d.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_galatd.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_game2d.D				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_game3d.D				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_gamesd.D				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_gellad.D				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_gerard.D				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_gilbad.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_hunted.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_ilenad.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_injurd.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_isleyd.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_kageid.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_karpdd.D				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_katred.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_lieded.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_lotusd.D				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_magnud.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_meredd.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_nagatd.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_nobled.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_opheld.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_quassd.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_rich2d.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_richad.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_rigald.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_rogued.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_saradd.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_smuggd.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_thamud.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_tuztdd.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_vapuld.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_xevecd.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_yumild.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_zedadd.d				--untraify-tra gorgon\lang\english\quests.tra				 
weidu --nogame 	--untraify-d gorgon\dialog\h_zhontd.d				--untraify-tra gorgon\lang\english\quests.tra


pause
